### ISSUE TITLE
Question: Do we want "No Clock" Block in 2.0?

### ISSUE THREAD

**Issue by pikurasa** [sugarlabs/musicblocks-2#19]
If we could design MB2.0 to not need the user to specify "No Clock", then I think it would be easier to use.

Perhaps, MB could infer from the structure of the code whether or not to use "No Clock" block.

Otherwise, we may need to give users some debugging "warnings", which may not be bad anyway.

**Comment by meganindya** [comment]
We intend to use a scheduler called `Transport`, provided by _tone.js_. One of the main objectives is ideally to cut down on a lot of the runtime complexity which causes unwanted drifting. Can't tell about the performance yet though.

**Comment by meganindya** [comment]
BTW you can create discussions now on this repository. See the _Discussions_ tab on top. There are 4 categories available too. We are already using that for the ideas and questions. Would be easier to bunch them together.

**Comment by walterbender** [comment]
https://github.com/sugarlabs/musicblocks-2/discussions/20
