### ISSUE TITLE
Show a splash screen at startup

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#221]
## Description

The current build has a start UI as:

![Screenshot 2022-11-06 at 9 23 16 PM](https://user-images.githubusercontent.com/33328728/200180812-0a7f83cc-059d-4a62-baa0-316f8f8f4fde.png)

However, if you notice, it takes a second to load and mount the components; the delay duration depends on the network and the compute power. This will inevitably increase as we add more components and complexity to the app. A splash screen is desirable which is among the first things to be loaded and stays in view until all the pieces have been loaded (like Music Blocks v3).

We don't have a design for it yet, however, the mechanics can mostly be implemented independently. It would be nice to also have a progress bar showing the loading progress.

## Objectives

- [x] Create a new `splash` component inside `src/view/components` having a fullscreen layout (feel free to come up with any simple freeform design as this is temporary; don't put too many pieces though)
- [x] Expose functions in `view/components/splash/index.ts` e.g. `mountSplash` and `updateSplash`
  - add a parameter `data` (which only has `progress` for now)
  - use `ReactDOM.render` to mount and update the splash component
- [ ] Add a key `splash: true` in `src/app/config/preset-0.ts` (you'll need to add it to the type definition `IAppConfig` as well)
- [ ] Make changes in `src/app/index.ts` (TBD)
  - Collect from `src/app/config` whether to show splash; if value is `false` jump to load main view step
  - Mount the splash component before loading other components
  Use the `setView` function defined in `src/view/index.ts` to set the splash component
  - Start the load operation (`setup` function defined in `src/config/index.ts` previously)
  - Set view to `main` after all components have completed loading and mounting

**Comment by V1C70RYG0D** [comment]
PR #232 
can you assign me this task 
as of now i have solved first task to create a splash component , kindly review my PR #232

**Comment by V1C70RYG0D** [comment]
Hi there,
@meganindya 
I was working on the second task and I'm a bit unsure about what is expected. Could you please provide more details about what you want me to do? I'm also wondering if the function is only for the splash component, and if so, any hints on what logic to include for the update function would be greatly appreciated.

Thanks for your help!

**Comment by meganindya** [comment]
There are two important aspects:
- mount and unmount the splash component
  See the `index.ts` files of components like `menu`, `painter` to get an idea
- updating load progress and reflecting that in the component
  See `config/index.ts` and try to understand how the components are loaded and mounted. You'll need to insert and reorganise code in that file to get an idea of the count of things that need to happen on load and iteratively when each item completes its load lifecycle.
  
I think your question is specific to the 2nd point mentioned above. For a start, try to figure out how many components are to be loaded. Then insert code in the load promises to increment count of an item loaded and mounted. Pass that information to your component. As a further iteration, it'd be nice to collect the checklist of components to be loaded and progressively display an updated checklist of when each component is loaded.

**Comment by meganindya** [comment]
Say components `x`, `y`, and `z` are supposed to be loaded.

Make a table like:

```ts
{
  x: false,
  y: false,
  z: false
}
```

In your component display, `0 of 3` or `0% of 100%` (perhaps a progress bar)

Say `y` has completed loading and mounting

Update the table as:

```ts
{
  x: false,
  y: true,
  z: false
}
```

In your component display, `1 of 3` or `33.33% of 100%` (progress bar at 33.33%)

As for the iteration, displaying the table as a checklist will be nice for debugging

**Comment by meganindya** [comment]
Note that this process can also happen quite fast depending on the server and the client's internet connection. Perhaps it'll be nice to have a minimum time counter of say 2 seconds to ensure the splash screen doesn't just flash, before it is unmounted.

**Comment by meganindya** [comment]
Basic workflow is:
1. mount the splash component when from the `main.ts` file (it is loaded before any components are loaded)
2. have the splash component interact with `config/index.ts` to gather information about component load progress
3. unmount the splash component when all components have completed loading and mounting

**Comment by V1C70RYG0D** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/96035378/210598000-229a3976-bee2-43f3-bce3-99b9f1833dfb.jpg)
Thank you for your help and for explaining what needed to be implemented. I have made some progress on implementing the splash screen and have added it to my repository. I had to make a few changes to the config/index.tsx file, but am still having some issues calling the mountSplash, updateSplash, and unmountSplash functions correctly.

I am trying to figure out the overall flow of the application to determine where these functions should be called. I have considered using the componentDidMount and componentWillUnmount lifecycle methods of the top-level component that the splash screen should be displayed within, or using a state management library like Redux or MobX to manage the visibility of the splash screen.

In the meantime, I have attached a screenshot of the splash screen running correctly. However, please note that you currently need to call the mount or update functions explicitly to test it. I will continue working on this issue and try to resolve it as soon as possible. Thank you again for your assistance.
git@github.com:VictoryGod18/musicblocks-v4-develop.git 

#235 

also i am going to explore V3 repository for the same.


UPDATE -> Succesfully integrated mount update and unmout 
Problems to solve -> after unmounting the app is not rendering correctly , its not loading , the splash screen do disappear after 2 sec but the screen with mouse and toolbar not showing

**Comment by V1C70RYG0D** [comment]
@meganindya 

Can you help me in writing unmount function

```
export function mountSplash() {
  ReactDOM.render(
    <Splash progress={0} />,
    document.getElementById('root'),
  );
}

export function updateSplash(componentCount : number, componentLoadedCount : number) {
  const progress = (componentLoadedCount / componentCount) * 100;
  ReactDOM.render(
    <Splash progress={progress} />,
    document.getElementById('root'),
  );
}

export function unmountSplash() {
  
}
```

everything is working fine but i am unable to unmountSplash
i used 
```
export function unmountSplash() {
  const rootElement = document.getElementById('root');
  if (rootElement) {
    ReactDOM.unmountComponentAtNode(rootElement);
  }
}
```

but this will show blank white screen afte unmounting , further code is working i tried by logging something to console

Thanks :)

**Comment by V1C70RYG0D** [comment]
kindly review this PR, i tried to follow contributors' guideline 
and sorry for the inconvenience caused previously as i am new.
