### ISSUE TITLE
Define dependencies in component

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#236]
## Description

The architecture of this application allows for components to be loaded and mounted dynamically. However, there can be 'optional' and 'required' dependencies between the components.

e.g. The **painter** component optionally depends on the **menu** component, while the **editor** component requires the **menu** component. Right now, the dependency is specified in the configuration files in `src/config/base*.json`. However, that can lead to errors.

The idea is to add a function in the `index.ts` file of each component to define the dependencies. The dependency tree in `src/config/index.ts` should be figured out from the dependencies defined by the component instead of using the `parent` field in the configuration file.

**Note:** The configuration files in `src/config/` need to be eventually replaced by a better style of feature flagging. But, that must be done iteratively, to prevent large refactoring PRs.

## Objectives

- [x] Add a `defineComponent` function in each component
  The function signature is as:
  ```ts
  interface IComponentConfig {
    id: string,
    dependencies: {
      ['component-id': string]: 'optional' | 'required'
    }
  }
  
  export function defineComponent(): IComponentConfig;
  ```
  Put the function in the root `index.ts` files of `editor`, `menu`, `painter`, `singer`. Add the interface in `@types/components/index.d.ts`.

- [x] Read the component definitions (added in previous step) in `src/config/index.ts` of the components defined in the configuration file/s and use that to define the dependency tree

- [x] Remove `parent` field from the configuration files

**Comment by V1C70RYG0D** [comment]
i am willing to work on this , as for the issue of splash screen , i have tried to understand this base.jsonc file , so i can try on this issue too!
 please assign me 
 
 (i will start working after 4-5 days)
 
 thanks!!

**Comment by kirtanchandak** [comment]
Hey, I want to work on this issue. I am done setting up the local development server, I want to know where should I start solving this issue ?

**Comment by meganindya** [comment]
Whoever wants to go ahead, take a shot. Assignment not required. Start by adding the `defineComponent` function in `src/components/editor/index.ts`, `.../menu/...`, `.../painter/...`, and ``.../singer/...``

**Comment by meganindya** [comment]
Make sure to follow the [contributing guidelines](https://github.com/sugarlabs/musicblocks-v4/blob/develop/docs/CONTRIBUTING.md)

**Comment by Arunjagan12** [comment]
what are all the remaining works after the above commit
