### ISSUE TITLE
Investigate error at startup

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#243]
On starting the application on the development server (`npm start`), I sometimes get an error in the browser console.

```console
Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at index.ts:42:1
```

The `index.ts` refers to [`src/components/painter/view/index.ts`](https://github.com/sugarlabs/musicblocks-v4/blob/develop/src/components/painter/view/index.ts).

This is most likely a race condition since I've seen this appear inconsistently.

**Comment by harsv689** [comment]
Since the error is inconsistent is it because of typescript is being executed by the browser before the dom is all defined ?

**Comment by meganindya** [comment]
Most likely that is the race condition.
