### ISSUE TITLE
Create resuable image components

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#247]
## Description

The application uses SVG icons. The benefit is that, being vectors, there is to pixelation on resizing, and we can change the fill colours as required.

However, to use an SVG image as an icon as `SVGElement` and not `HTMLImageElement`, we either need to embed the SVG markup within the component markup, or import the markup text and set it as the `innerHTML` property of its container. For modularity, we need to follow the latter (so we can have separate `.svg` files).

So, for code reusability, we need to separate out the utilities of loading and embedding an SVG from the 'view' files of the components.

## Objectives

- [ ] Create `src/assets/image/icon/` and copy all `.svg` files to it
- [ ] Add entries to `manifest` in `src/assets/index.ts`
- [ ] Create `index.tsx` and `index.scss` in `src/common/components/ImageVector/` as:
  - `index.tsx`
    - Create the React functional component definition (add a wrapper component which will eventually include the `SVGElement` markup as it's child)
      ```tsx
      /**
       * <replace with full function documentation of the React component>
       */
      export default function (props: ...): JSX.Element {
        // implementation of the function
        ...
      }
      ```
    - Asset identifier will be the prop to the component
    - Import `getAsset` from `@/core`
    - Get svg text by calling `getAsset('image', '<identifier>').data`
    - Import `index.scss`
  - `index.scss`
    SCSS code for the `ImageVector` component

**Comment by meganindya** [comment]
Please make independent commits (logical separation of concepts). Address issue one objective point at a time.

**Comment by disha1202** [comment]
Hi @meganindya,
I would like to work on this.

**Comment by meganindya** [comment]
Go ahead, no need to ask
