### ISSUE TITLE
Add feature to toggle feature flags in the UI

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#248]

**Comment by Tushar98644** [comment]
i would to contribute to it @meganindya , can you be a bit more specific about what i have to do?

**Comment by meganindya** [comment]
This is sort of convoluted, so I'm currently doing this. Look out for unassigned open issues. I'll add quite a few in the coming days.

**Comment by Tushar98644** [comment]
> This is sort of convoluted, so I'm currently doing this. Look out for unassigned open issues. I'll add quite a few in the coming days.

i don't think there are any more open issues out there , when will beginner friendly new issues be added?

**Comment by meganindya** [comment]
#221, #261, #272, #275
