### ISSUE TITLE
Find a way to inject a JSON object into the vite dev server

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#275]
I need to access some runtime information. When you build the project a `stats.json` file is created. However, it is not generated during development.

Find a way, if possible, to inject a JSON object accessible at runtime when serving from the dev server.

**Comment by Manoramsharma** [comment]
Hi @meganindya looking forward to work on this issue, It would be great if you can guide me through exactly the target project we are talking about here.

**Comment by meganindya** [comment]
I actually have a WIP. See branch [288-bundle-sizes-splash-progress](https://github.com/sugarlabs/musicblocks-v4/tree/288-bundle-sizes-splash-progress). Please look out for other issues.

**Comment by V1C70RYG0D** [comment]
@meganindya , there are two ways to make the JSON object accessible at runtime when serving from the dev server is to use webpack's ``DefinePlugin`` to define the JSON object as a global variable.

You can do this by adding the following to your webpack configuration file:

```
const path = require('path');
const webpack = require('webpack');

module.exports = {
    // ...
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                'STATS_JSON': JSON.stringify(require(path.resolve(__dirname, 'stats.json')))
            }
        })
    ]
};

```

this will make the contents of the `stats.json` file available as a global variable `process.env.STATS_JSON` which you can access in your code.

else

 you can use a package like `dotenv`to load environment variable from a .env file during development. In this case, you can write the stats.json file to the .env file and read the variable during runtime.
