### ISSUE TITLE
Enhancement of Toggle switch UI 

### ISSUE THREAD

**Issue by Tushar98644** [sugarlabs/musicblocks-2#295]
While viewing the components in storybook i found that the toggle switch has a rather outdated uI:

<img width="1440" alt="Screenshot 2023-01-21 at 9 39 58 PM" src="https://user-images.githubusercontent.com/107763774/213876107-76a9578e-5c42-4a48-94ce-44551e4f6906.png">

It can be enhanced to look something like this:

<img width="989" alt="Screenshot 2023-01-21 at 9 42 50 PM" src="https://user-images.githubusercontent.com/107763774/213876139-c0ec8ded-8116-4f4a-810b-8f6d34d8186b.png">
<img width="990" alt="Screenshot 2023-01-21 at 9 43 09 PM" src="https://user-images.githubusercontent.com/107763774/213876141-dee79535-7cfb-471b-a940-18660d24099f.png">

**Comment by Tushar98644** [comment]
@meganindya can i work on this?

**Comment by meganindya** [comment]
Thx. updated #272 and the mockups. Please do not replace the existing component. Add a new one as mentioned.

Use `$c-bg-white`, `$c-bg-grey`, and `$c-bg-shadow` for colors.

**Comment by Tushar98644** [comment]
> Thx. updated #272 and the mockups. Please do not replace the existing component. Add a new one as mentioned.
> 
> Use `$c-bg-white`, `$c-bg-grey`, and `$c-bg-shadow` for colors.

yes sure , will add a new component and create a pr by tomorrow...
