### ISSUE TITLE
[Bug] Script failing to generate the i18n and assets sizes while building

### ISSUE THREAD

**Issue by niloysikdar** [sugarlabs/musicblocks-2#302]
I tried the branch [288-bundle-sizes-splash-progress](https://github.com/sugarlabs/musicblocks-v4/tree/288-bundle-sizes-splash-progress) (by @meganindya) to test the code and found one issue with that.

Note: I'm using `Windows 10 OS` that means `win32` platform. The issue isn't happening for `linux` and `darwin` platform as confirmed by @meganindya

I ran `npm run build` and checked the generated `dist/stats.json` file data.
However, I found the `i18n` and `assets` data to be missing.

```json
{
  "i18n": {},
  "assets": {},
  "modules": { "menu": 1394, "singer": 226021, "editor": 35200, "painter": 219016 }
}
```

I double checked to make sure the data is actually present in the `i18n` and `assets` dirMaps, and found that there is some data for both keys.

I then deep dived into the functions and how the data is getting generated and found the bug.

Firstly, when we are saving the `VisualizerData` into the `dist/stats.json` file, we are getting the Absolute Paths of the files inside the `id` of `nodeMetas`.

The `path` module works differently for the `win32` based systems than of `linux` or `darwin`. More info can be found here: [https://nodejs.org/api/path.html#windows-vs-posix](https://nodejs.org/api/path.html#windows-vs-posix)

Here is a glimpse of the generated `VisualizerData` with the `AST (Abstract syntax tree)` information.

```json
{
  "version": 2,
  "tree": {},
  "nodeParts": {},
  "nodeMetas": {
    "57d3-1762": {
      "id": "\u0000commonjs-dynamic-modules",
      "moduleParts": {
        "assets/_commonjs-dynamic-modules-302442b1.js": "57d3-1763"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-2830"
        },
        {
          "uid": "57d3-1992"
        },
        {
          "uid": "57d3-2006"
        }
      ]
    },
    "57d3-1764": {
      "id": "C:/Users/HP/Desktop/Web/musicblocks-v4/src/core/events/index.ts",
      "moduleParts": {
        "assets/index-97cad2bf.js": "57d3-1765"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-2034"
        },
        {
          "uid": "57d3-1796"
        },
        {
          "uid": "57d3-2848"
        }
      ]
    },
    "57d3-1766": {
      "id": "C:/Users/HP/Desktop/Web/musicblocks-v4/src/core/i18n/lang/en.ts",
      "moduleParts": {
        "assets/lang.en-a09fe94b.js": "57d3-1767"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-1782"
        }
      ],
      "isEntry": true
    },
    "57d3-1768": {
      "id": "C:/Users/HP/Desktop/Web/musicblocks-v4/src/core/i18n/lang/es.ts",
      "moduleParts": {
        "assets/lang.es-5dc320b5.js": "57d3-1769"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-1782"
        }
      ],
      "isEntry": true
    },
    "57d3-1770": {
      "id": "C:/Users/HP/Desktop/Web/musicblocks-v4/src/components/index.ts",
      "moduleParts": {
        "assets/index-0b306afc.js": "57d3-1771"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-1778"
        },
        {
          "uid": "57d3-2104"
        }
      ]
    },
    "57d3-1772": {
      "id": "\u0000vite/preload-helper",
      "moduleParts": {
        "assets/dynamic-import-helper-cd46bf53.js": "57d3-1773"
      },
      "imported": [],
      "importedBy": [
        {
          "uid": "57d3-1778"
        },
        {
          "uid": "57d3-1782"
        },
        {
          "uid": "57d3-1834"
        },
        {
          "uid": "57d3-1830"
        }
      ]
    },
  },
  "env": {
    "rollup": "3.10.1"
  },
  "options": {
    "gzip": true,
    "brotli": false,
    "sourcemap": false
  }
}
```

That's why `id.startsWith(prefix)` is failing in [scripts/stats/index.ts#L55](https://github.com/sugarlabs/musicblocks-v4/blob/288-bundle-sizes-splash-progress/tools/scripts/stats/index.ts#L55) and it is basically returning an empty array.

One simple solution is to put a platform check using `process.platform` and detect if the platform is `win32`; and use `id.includes(prefix)` instead of `id.startsWith(prefix)`, but then again we need to fix the logic to structure the key in [scripts/stats/index.ts#L57](https://github.com/sugarlabs/musicblocks-v4/blob/288-bundle-sizes-splash-progress/tools/scripts/stats/index.ts#L57) to actually remove the root path from the `Absolute Path` and then replace the `prefix` with an empty string to only get the fileName as the key.

More discussion and context can be found [here](https://github.com/sugarlabs/musicblocks-v4/issues/288#issuecomment-1399603559)

Related issue: #288 

CC @meganindya

**Comment by niloysikdar** [comment]
Is this generated `stats.json` correct? @meganindya

```json
{
  "i18n": { "en": 104, "es": 120 },
  "assets": {
    "image/logo.png": 65,
    "image/icon/build.svg": 70,
    "image/icon/help.svg": 69,
    "image/icon/pin.svg": 68,
    "image/icon/unpin.svg": 70,
    "image/icon/run.svg": 68,
    "image/icon/stop.svg": 69,
    "image/icon/reset.svg": 70,
    "image/icon/saveProjectHTML.svg": 80,
    "image/icon/exportDrawing.svg": 78,
    "image/icon/startRecording.svg": 79,
    "image/icon/stopRecording.svg": 78,
    "image/icon/close.svg": 70,
    "image/icon/code.svg": 69,
    "image/icon/mouse.svg": 70
  },
  "modules": { "menu": 1394, "editor": 35200, "singer": 226021, "painter": 219016 }
}
```

**Comment by meganindya** [comment]
Yes. Would you like to complete the remainder of the issue I was working on? There's a function that you need to implement. I shared the line number on the other discussion.

**Comment by niloysikdar** [comment]
Yes, I noticed that also. Will submit that implementation in a separate PR which will close #288

**Comment by niloysikdar** [comment]
Submitted the PR [here](https://github.com/sugarlabs/musicblocks-v4/pull/307)

@meganindya

**Comment by meganindya** [comment]
There's more work related to asset path handling. As you can see I generate asset size data based on path, but in the app, the bundled path is listed, e.g. `assets/logo-abc1234.svg`. We need to find a way to map between these, or better list the bundled path in the stats (currently the bundled paths are not found in the stats file). But, that's another issue.

**Comment by niloysikdar** [comment]
Gotcha, we can discuss this topic further on how to go ahead.

**Comment by niloysikdar** [comment]
Hmm, seems like we need solid mapping to handle the calculations between the `stats` and `data: TAppImportMap` in order to update our loading progress.

Should we change the assets' keys formats in the `stats.json` itself to map that to the data?
Something like `image/icon/build.svg` will get changed to `image.icon.build`

Or we keep the stats' keys as it is and compare the mapping inside our `updateSplashData` method to check which assets we need to load and what is the size?

What's your opinion on this? @meganindya

**Comment by meganindya** [comment]
That was my first instinct but that still is flaky. `image.icon.build` is just another string and may not necessarily map to `image/icon/build.ext`. Also there could be a same file with a different extension in the same location.

Ideally the stats file must bundle the image as `build-123abcd.ext` and that can be found from the inline path in the app. But the bundled file names aren't found in the `stats.json` generated by the visualizer because those aren't `.js` files. I didn't look into the causes of this very much. Perhaps it is something you could look into?

**Comment by niloysikdar** [comment]
Seems like we need more discussion on this.

**Comment by meganindya** [comment]
Please hit me up on matrix. We can discuss tomorrow.

**Comment by niloysikdar** [comment]
Yup sure. Are you in IST timezone or any other one?

**Comment by meganindya** [comment]
yes IST

**Comment by niloysikdar** [comment]
Texted you on matrix. @meganindya
