### ISSUE TITLE
[Bug]  Vite :Remove hashcodes from output build filenames 

### ISSUE THREAD

**Issue by Tushar98644** [sugarlabs/musicblocks-2#312]
@meganindya currently while creating a production build using vite , the output names in the 'dist/assets/'  folder come with hashed codes filenames by default , we can remove the hashcodes and generate the filenames without hashcodes for better optimization..

**Comment by Tushar98644** [comment]
@meganindya  pls verify if it's a valid issue or not..

**Comment by meganindya** [comment]
I do not agree. Hash codes identify a particular version of a file. If the code changes, the hash changes. If hashes are removed, the browser won't know if the file has been modified, and might cache and serve the old file. That is not desirable.

**Comment by Tushar98644** [comment]
> I do not agree. Hash codes identify a particular version of a file. If the code changes, the hash changes. If hashes are removed, the browser won't know if the file has been modified, and might cache and serve the old file. That is not desirable.

Is there a workaround for generating filenames without hash codes and the browser updating the cache changes? .....otherwise while searching for a file in the build folder gets really confusing
