### ISSUE TITLE
Give the Upload File and Load Project some Icons

### ISSUE THREAD

**Issue by mayank190801** [sugarlabs/musicblocks-2#315]
As of now there is no icon for both upload file and load project feature. This could be fixed with temporary set of new icons and some changes in structure of JSX element for doing so.

![Screenshot 2023-02-01 at 1 53 02 AM](https://user-images.githubusercontent.com/54149585/215874349-4678ca68-0c82-47b7-af61-c2472bcdbb65.png)

**Comment by abhijain2003** [comment]
I think you are talking about first one,  and fifth one having, choose button instead of icons, but what Icons you are expecting , can I work on this?

**Comment by mayank190801** [comment]
I have already made a pull request for this issue. Check it once. If you have some better suggestion for the icons please let me know.

**Comment by meganindya** [comment]
Those icons are just placeholders for now. Will eventually get replaced with high fidelity icons when we get to the point of finalising the UI. Thx for the PR.
