### ISSUE TITLE
Fix bugs in brick path utility

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#339]
There are some bugs in the path designs that show up for certain arguments. Identify and fix those.

**Comment by niloysikdar** [comment]
Here are some of the bugs which we got for the `generatePath` utility function

<img src="https://github.com/sugarlabs/musicblocks-v4/assets/58071992/6cf719d6-7027-4141-8210-b0cfc550a011" width="400px" />
<img src="https://github.com/sugarlabs/musicblocks-v4/assets/58071992/1966b8cd-a013-4b08-97b1-aac16dbd9b6b" width="400px" />
<img src="https://github.com/sugarlabs/musicblocks-v4/assets/58071992/f6f79d24-fc47-4d67-8c97-967eaea9db0d" width="400px" />

We're getting this top-left distortion issue for the following combination of arguments:
`hasNotchArg: true && hasNotchInsTop: false`
