### ISSUE TITLE
Calculate bounding boxes in brick path utility

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-2#341]
## Description

Currently, the path utility in `code-builder/src/brick/design0/utils/path.ts` doesn't return the correct extents and co-ordinates data.

## Objectives

- [x] Return data for all bounding boxes
  - [x] `bBoxBrick`
  - [x] `bBoxNotchArg`
  - [x] `bBoxNotchInsTop`
  - [x] `bBoxNotchInsBot`
  - [x] `bBoxNotchInsNestTop`
  - [x] `bBoxArgs`
- [x] Add a flag in the brick components, enabling which draws the bounding boxes (rectangles of different outline colours) over the bricks, to visually verify the calculations are correct
- [x] Complete `it.todo` tests in `path.spec.ts`

**Comment by niloysikdar** [comment]
@meganindya, I think we can close it as it got completed.

**Comment by hackorlyf** [comment]
@niloysikdar @meganindya Is it a resolved issue or can I work on it?
