### ISSUE TITLE
editor is not closing when you click on its text!

### ISSUE THREAD

**Issue by Sumit-pd** [sugarlabs/musicblocks-2#365]
When you click on the </> on the top left on the screen and click on the editor you will not be able to turn it back off

**To Reproduce**
1. Go to http://localhost:5173/
2. Click on </> on top left of the screen
3. click on the text inside the editor
4. when you click on </> you will not be able to close the editor

**Expected behavior**
The editor should be closed!

**Screenshots**
https://github.com/sugarlabs/musicblocks-v4/assets/88550925/1dbb585a-a333-47c5-ad0a-39e94ba911fb

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : Chrome
 - Version : 22.04.2 LTS

**Additional context**
@walterbender @meganindya can you review this issue

**Comment by gauravsingh94** [comment]
It works fine; please ensure that you are using the updated version.

[Screencast from 2023-11-02 23-35-46.webm](https://github.com/sugarlabs/musicblocks-v4/assets/99260988/00f1b9c6-410e-4b54-ac0c-7cd1cf297a92)

**Comment by Sumit-pd** [comment]
thanks @gauravsingh94 for the info!
